<?php

/**
 * @see hook_node_postsave()
 */
    use Drupal\node\Entity\Node;
    use Drupal\file\Entity\File;
    use Drupal\field\Entity\FieldConfig;
    use Drupal\field\Entity\FieldStorageConfig;

function generate_parcours_node_postsave($node, $op) {
    // Si le content type est ma_descente (Parcours)
    if($node->type == 'ma_descente'){
  watchdog('generate_parcours', "The {$op}d node {$node->type} id is {$node->nid} from " . __FUNCTION__);
        shell_exec("mkdir -p /tmp/parcours/parcours_'{$node->nid}'");
        shell_exec("./drush.phar node-export-export '{$node->nid}' --format=JSON --file=/tmp/parcours/parcours_'{$node->nid}'/AllNodes.txt");
        shell_exec("cp -p sites/all/themes/cdm/bash/parcours_export.sh /tmp/parcours/parcours_'{$node->nid}'/parcours_export.sh");
        shell_exec("cp -p sites/all/themes/cdm/bash/Model.py /tmp/parcours/parcours_'{$node->nid}'/Model.py; cp -p sites/all/themes/cdm/bash/WaitForZip.sh /tmp/parcours/parcours_'{$node->nid}'/WaitForZip.sh; cd /tmp/parcours/parcours_'{$node->nid}'/; ./WaitForZip.sh; cp -a Parcours.zip /private_files/parcours/parcours_'{$node->nid}'.zip");
        shell_exec("rm -R /tmp/parcours/parcours_'{$node->nid}'/");
  
        $parcours_name = "parcours_{$node->nid}.zip";
        $uri = 'private://parcours/'. $parcours_name;

        $file = file_save((object) array(
          'filename' => basename($uri),
          'uri' => $uri,
          'status' => FILE_STATUS_PERMANENT,
          'filemime' => file_get_mimetype($uri),
        ));
        }
    }



    /*
     *  postinsert
     */

    
    function generate_parcours_node_postinsert($node){
        if($node->type == 'ma_descente'){
      watchdog('generate_parcours', "The inserted node {$node->type} id is {$node->nid} from " . __FUNCTION__);

 
            
            $thenodeid= $node->nid;

        $parcours_name = "parcours_{$node->nid}.zip";
        $file_path = "/system/files/parcours/{$parcours_name}";
        $node = node_load("$thenodeid");

     $node->field_linked_files[LANGUAGE_NONE][0]['value'] = "<a href=\"/system/files/parcours/{$parcours_name}\" class=\"btn btn-default btn-dark btn-xs\" ><i class=\"glyphicon glyphicon-download-alt\"></i> Télécharger</a>";
    field_attach_presave('node', $node);
    field_attach_update('node', $node);
        
        
    }
}
