<?php

/**
 * @see hook_node_postsave()
 */
    use Drupal\node\Entity\Node;
    use Drupal\file\Entity\File;
    use Drupal\field\Entity\FieldConfig;
    use Drupal\field\Entity\FieldStorageConfig;

//    function generate_parcours_node_save($node){
//
//        watchdog('generate_parcours', "the node save hook node save {$node->type} id is {$node->nid} from " . __FUNCTION__);
//}

    
    

    
    function generate_parcours_node_postsave($node, $op) {

//    if (arg(2) == 'add') {
    // Si le content type est ma_descente (Parcours)
    if($node->type == 'ma_descente'){
  watchdog('generate_parcours', "The {$op}d node {$node->type} id is {$node->nid} from " . __FUNCTION__);
        // On update Supprimer le fichier original
        $parcours_name = "parcours_{$node->nid}.zip";
        $uri = 'public://parcours/'. $parcours_name;
        shell_exec("mkdir -p /tmp/parcours/parcours_'{$node->nid}'");
        shell_exec("./drush.phar node-export-export '{$node->nid}' --format=JSON --file=/tmp/parcours/parcours_'{$node->nid}'/AllNodes.txt");
        shell_exec("cp -p sites/all/themes/cdm/bash/parcours_export.sh /tmp/parcours/parcours_'{$node->nid}'/parcours_export.sh");
        shell_exec("cp -p sites/all/themes/cdm/bash/Model.py /tmp/parcours/parcours_'{$node->nid}'/Model.py");
        shell_exec("echo '{$node->nid}' > /tmp/parcours/parcours_'{$node->nid}'/NID");
     }
    }

    /*
     *          postinsert
     */
    function generate_parcours_node_postinsert($node){
        if($node->type == 'ma_descente'){
      watchdog('generate_parcours', "The inserted node {$node->type} id is {$node->nid} from " . __FUNCTION__);
        $thenodeid= $node->nid;
        $parcours_name = "parcours_{$node->nid}.zip";
        $file_path = "/sites/default/files/parcours/{$parcours_name}";
        $node = node_load("$thenodeid");
        $node->field_linked_files[LANGUAGE_NONE][0]['value'] = "/sites/default/files/parcours/{$parcours_name}";
    field_attach_presave('node', $node);
    field_attach_update('node', $node);
    }
}
    
  

    function generate_parcours_node_post_update($node){
            if($node->type == 'ma_descente'){
          // your overriding code here

        
        watchdog('generate_parcours', "the noe_update node hook node update is {$node->type} id is {$node->nid} from " . __FUNCTION__);
            // On update Supprimer le fichier original
            $parcours_name = "parcours_{$node->nid}.zip";
            $uri = 'public://parcours/'. $parcours_name;
            shell_exec("mkdir -p /tmp/parcours/parcours_'{$node->nid}'");
            shell_exec("./drush.phar node-export-export '{$node->nid}' --format=JSON --file=/tmp/parcours/parcours_'{$node->nid}'/AllNodes.txt");
            shell_exec("cp -p sites/all/themes/cdm/bash/parcours_export.sh /tmp/parcours/parcours_'{$node->nid}'/parcours_export.sh");
            shell_exec("cp -p sites/all/themes/cdm/bash/Model.py /tmp/parcours/parcours_'{$node->nid}'/Model.py");
            shell_exec("echo '{$node->nid}' > /tmp/parcours/parcours_'{$node->nid}'/NID");
}
}
